mode: "backtest"   # options: backtest, live
start: "2025-01-01"
end: "2025-06-30"
output_dir: "data/raw"
features_dir: "data/features"
live_interval_sec: 60   # only for live mode

mt5:
  login: 1511628126
  password: "9Z$DnXq75l*7ev"
  server: "FTMO-Demo"
  path: "C:/Program Files/MetaTrader 5/terminal64.exe"

ccxt:
  exchange_id: "binance"
  api_key: "your_api_key"
  secret: "your_secret"

assets:
  - symbol: "EURUSD"
    source: "mt5"
    timeframes: ["5m","15m","1h"]
    cost_model:
      type: "forex"
      commission:
        kind: "usd_per_lot_roundtrip"
        value: 3.0           # $3 roundtrip
        pip_value_per_lot_usd: 10.0   # optional override; sonst aus MT5 symbol_info
  - symbol: "GBPUSD"
    source: "mt5"
    timeframes: ["5m","15m","1h"]
    cost_model:
      type: "forex"
      commission:
        kind: "usd_per_lot_roundtrip"
        value: 3.0
  - symbol: "US500.cash"
    source: "mt5"
    timeframes: ["5m","15m","1h"]
    cost_model:
      type: "index"
      commission:
        kind: "usd_per_lot_roundtrip"
        value: 0.0
        # Bei Indizes ist pip/point anders; MT5 liefert tick_value -> wird automatisch in pips umgerechnet

        
  # - symbol: "BTC/USDT"
  #   source: "ccxt"
  #   timeframes: ["1m","15m"]
  #   cost_model:
  #     type: "crypto"
  #     commission:
  #       kind: "perc"
  #       perc: 0.0004    # 0.04% roundtrip als Beispiel
